import './globals.css'
import type { Metadata } from 'next';

import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Notification from '@/components/Notification';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='font-poppins overflow-x-hidden ' >
        <div>
          <Notification />
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
